### ISSUE TITLE
[BUG] Trying to fetch the firmware index results in HTTP error 404

### ISSUE THREAD

**Issue by ludanin** [ThePBone/GalaxyBudsClient#248]
**Describe the bug**  
Trying to fetch the firmware index results in HTTP error 404

**To Reproduce**  
Just go to Firmware updates, if no updates are available click on firmware downgrading (I don't know if this happens when updating, I'm trying to downgrade)

**Expected behavior**  

**Screenshots**  
![image](https://user-images.githubusercontent.com/31702297/128498785-e6adcc44-2339-4124-8cfb-4e11af5d89b5.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10 (Build 19042.1110)
 - Application version: 4.2.0.0

**Additional context**  
I updated my Buds+ yesterday and for the first time ever since I bought them I'm experiencing some issues, I discovered this app after finding someone with similar problems in a reddit thread (the person even went as far as to say that this is planned by Samsung since Buds 2 are coming next week haha). Regardless if it's just a bug or not, I tried downgrading using this app, but I can't download the firmware index.

Tbh I'm glad I ran into this issue, I didn't know about this client before and the official one from Samsung doesn't allow me to change the settings using my PC, I wish I could star this repo twice, so thanks for the great work! 🙌 🌟 

**Log files**  
```
2021-08-06 07:45:06.346 -03:00 [DBG] FirmwareRemoteClient: Searching for firmware binaries...
2021-08-06 07:45:07.474 -03:00 [ERR] FirmwareRemoteClient: Search failed: The cloud file provider exited unexpectedly.
2021-08-06 07:45:07.474 -03:00 [ERR] FirmwareSelectionPage.RefreshList: System.Net.NetworkInformation.NetworkInformationException (404): The cloud file provider exited unexpectedly.
   at GalaxyBudsClient.Model.Firmware.FirmwareRemoteClient.SearchForFirmware(Boolean allowDowngrade)
   at GalaxyBudsClient.Interface.Pages.FirmwareSelectionPage.RefreshList(Boolean user)
```

**Comment by ThePBone** [comment]
Thanks for reporting the bug! 
It looks like I had an error in the VirtualHost config of my server.

Anyway, the firmware archive is now accessible again.
