### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by btodorce** [ThePBone/GalaxyBudsClient#271]
[14:58:31 ERR] System.TypeInitializationException: The type initializer for 'GalaxyBudsClient.Platform.MediaKeyRemoteImpl' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libX11' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibX11: cannot open shared object file: No such file or directory
   at Tmds.DBus.Interop.XOpenDisplay(String name)
   at Tmds.DBus.Address.GetSessionBusAddressFromX11()
   at Tmds.DBus.Address.get_Session()
   at ThePBone.MprisClient.MprisClient..ctor()
   at GalaxyBudsClient.Platform.Linux.MediaKeyRemote..ctor()
   at GalaxyBudsClient.Platform.MediaKeyRemoteImpl..cctor()
   --- End of inner exception stack trace ---
   at GalaxyBudsClient.Platform.MediaKeyRemoteImpl.Init()
   at GalaxyBudsClient.App.Initialize()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at GalaxyBudsClient.Program.Main(String[] args)

It crashes at startup, the app has been granted +x permissions
OS: pop_os!
Lenovo Idea pad gaming 3,
Nvidia gtx 1650ti mobile, with 470.63.01 proprietary drivers

**Comment by btodorce** [comment]
Resolve ignore it, missed the obvious error Unable to load shared library 'libX11'

**Comment by ThePBone** [comment]
Try to install the X11 server if it's not installed, but normally this is auto-detected.

If you're on NixOS, it looks like they might set the `LD_LIBRARY_PATH` incorrectly. More about this here: https://github.com/AvaloniaUI/Avalonia/issues/3020
