### ISSUE TITLE
[BUG] System.Globalization.Invariant Flag Causes Launch to Fail. [Linux]

### ISSUE THREAD

**Issue by varad-kadam** [ThePBone/GalaxyBudsClient#331]
**Describe the bug**  
Launching the Galaxy Buds Client through the app causes it to fail/force close. Launching through the terminal:
```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at Interop+procfs.GetStatFilePathForProcess(Int32)
   at Interop+procfs.TryReadStatFile(Int32, ParsedStat ByRef, System.Text.ReusableTextReader)
   at System.Diagnostics.Process.GetStat()
   at System.Diagnostics.Process.get_StartTimeCore()
   at System.Diagnostics.Process.get_StartTime()
   at Sentry.Internal.ProcessInfo.GetStartupTime()
   at Sentry.Internal.ProcessInfo.<.ctor>b__14_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Aborted (core dumped)
```

**Desktop:**  
 - OS: EndeavourOS Linux x86_64
 - Kernel: 5.17.7 
 - Application version: galaxybudsclient-bin 4.4.1-3

**Solution:**
[This Stackoverflow Issue](https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in) contains the solution.
Running `export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` before launching fixes the issue. I was wondering if there was a way to integrate this into the app.

**Comment by ThePBone** [comment]
This bug should be fixed in the [latest version](https://github.com/ThePBone/GalaxyBudsClient/releases).

See https://github.com/ThePBone/GalaxyBudsClient/issues/314 for details.
