### ISSUE TITLE
[CRSH]  (without BT enabled/plugged in)

### ISSUE THREAD

**Issue by AndKe** [ThePBone/GalaxyBudsClient#409]
started the app, without enabling BT first

**Include event files here**
Ubuntu 23.04:

```
$ ./GalaxyBudsClient_Linux_amd64_Portable.bin 
[09:08:47 INF] Using settings file at: /home/andre/.local/share/GalaxyBudsClient/config.json
[09:08:48 INF] SingleInstanceWatcher: Server listening at tcp:host=127.0.0.1,port=54532
[09:08:49 DBG] BluetoothImpl: Using Linux.BluetoothService
[09:08:49 INF] Translator mode file location: /home/andre/.local/share/GalaxyBudsClient/custom_language.xaml
[09:08:49 INF] User script directory: /home/andre/.local/share/GalaxyBudsClient/scripts
[09:08:49 INF] ScriptManager: 0 user script(s) found
[09:08:49 DBG] MainWindow.Instance: Initializing window with default WindowImpl
[09:08:49 WRN] StubDeviceSpec: initialized
[09:08:49 DBG] FirmwareRemoteClient: Searching for firmware binaries...
GalaxyBudsClient Warning: 0 : Attribute 'stroke-dasharray' cannot be set - type 'Svg.SvgPath' cannot convert from string 'null'.
GalaxyBudsClient Warning: 0 : Attribute 'stroke-width' cannot be set - type 'Svg.SvgPath' cannot convert from string 'null'.
[09:08:50 WRN] Dummy.HotkeyReceiver: Platform not supported
[09:08:50 DBG] FirmwareRemoteClient: 0 firmware found.
[09:09:14 ERR] Tmds.DBus.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at ThePBone.BlueZNet.BlueZManager.GetProxiesAsync[T](String interfaceName, IDBusObject rootObject)
   at ThePBone.BlueZNet.BlueZManager.GetAdaptersAsync()
   at GalaxyBudsClient.Bluetooth.Linux.BluetoothService.SelectAdapter(String preferred)
   at GalaxyBudsClient.Bluetooth.Linux.BluetoothService.GetDevicesAsync()
   at GalaxyBudsClient.Platform.BluetoothImpl.GetDevicesAsync()
   at GalaxyBudsClient.Interface.Pages.DeviceSelectionPage.RefreshList(Boolean user)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at GalaxyBudsClient.Program.Main(String[] args)

```

**Additional context**

**Comment by ThePBone** [comment]
Thanks, fixed 8954ecf0
