### ISSUE TITLE
[CRSH] App crashes on launch (Fedora Workstation 38)

### ISSUE THREAD

**Issue by stardustspirit** [ThePBone/GalaxyBudsClient#418]
**Shortly describe what were you doing before crash**
The app crashes immediately after being launched. The window shows for a second, but that's it. I've never used the app before.

**Include event files here**
```
[22:24:23 INF] Using settings file at: /home/logicalwillow/.var/app/me.timschneeberger.GalaxyBudsClient/data/GalaxyBudsClient/config.json
[22:24:24 INF] SingleInstanceWatcher: Server listening at tcp:host=::1,port=54532
[X11Platform] SMLib/ICELib reported a new error: None of the authentication protocols specified are supported (X11PlatformLifetimeEvents #51998856)
[22:24:27 DBG] BluetoothImpl: Using Linux.BluetoothService
[22:24:27 INF] Translator mode file location: /home/logicalwillow/.var/app/me.timschneeberger.GalaxyBudsClient/data/GalaxyBudsClient/custom_language.xaml
[22:24:27 INF] User script directory: /home/logicalwillow/.var/app/me.timschneeberger.GalaxyBudsClient/data/GalaxyBudsClient/scripts
[22:24:27 INF] ScriptManager: 0 user script(s) found
[22:24:27 DBG] MainWindow.Instance: Initializing window with default WindowImpl
[22:24:27 WRN] StubDeviceSpec: initialized
[22:24:27 DBG] FirmwareRemoteClient: Searching for firmware binaries...
GalaxyBudsClient Warning: 0 : Attribute 'stroke-dasharray' cannot be set - type 'Svg.SvgPath' cannot convert from string 'null'.
GalaxyBudsClient Warning: 0 : Attribute 'stroke-width' cannot be set - type 'Svg.SvgPath' cannot convert from string 'null'.
[22:24:28 WRN] Dummy.HotkeyReceiver: Platform not supported
[22:24:28 ERR] Tmds.DBus.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: unit failed.
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at ThePBone.BlueZNet.BlueZManager.GetProxiesAsync[T](String interfaceName, IDBusObject rootObject) in /run/build/GalaxyBudsClient/ThePBone.BlueZNet/BlueZManager.cs:line 53
   at ThePBone.BlueZNet.BlueZManager.GetAdaptersAsync() in /run/build/GalaxyBudsClient/ThePBone.BlueZNet/BlueZManager.cs:line 45
   at GalaxyBudsClient.Bluetooth.Linux.BluetoothService.SelectAdapter(String preferred) in /run/build/GalaxyBudsClient/GalaxyBudsClient.Bluetooth.Linux/BluetoothService.cs:line 88
   at GalaxyBudsClient.Bluetooth.Linux.BluetoothService.GetDevicesAsync() in /run/build/GalaxyBudsClient/GalaxyBudsClient.Bluetooth.Linux/BluetoothService.cs:line 400
   at GalaxyBudsClient.Platform.BluetoothImpl.GetDevicesAsync() in /run/build/GalaxyBudsClient/GalaxyBudsClient/Platform/BluetoothImpl.cs:line 181
   at GalaxyBudsClient.Interface.Pages.DeviceSelectionPage.RefreshList(Boolean user) in /run/build/GalaxyBudsClient/GalaxyBudsClient/Interface/Pages/DeviceSelectionPage.xaml.cs:line 179
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 181
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at GalaxyBudsClient.Program.Main(String[] args) in /run/build/GalaxyBudsClient/GalaxyBudsClient/Program.cs:line 131
```

**Desktop (please complete the following information):**
 - OS: Fedora Workstation 38 (GNOME, Wayland)
 - Application version: 4.5.2, Flathub

**Additional context**
My Galaxy Buds weren't paired when I tried to launch the app, but it still seems weird that the app crashes

**Comment by ThePBone** [comment]
The application failed to connect to Bluez (Bluetooth stack) via the D-Bus.
Make sure that the Bluez service is active. Otherwise, this may be some issue with the flatpak packaging/sandbox, however, I'm unable to reproduce it if that's the case.
